### ISSUE TITLE
Duvidas

### ISSUE THREAD

**Issue by JEOSAFAELLER** [igorkeven/criando-formulario-de-cadastro-para-o-login#1]
olá, você instalou algum simulador de servidor?
ou qual npm ?
estou fazendo um trabalho de faculdade, e preciso fazer uma tela de login bem semelhante a essa.
obrigado.

**Comment by igorkeven** [comment]
não precisa, uso o servidor local, o localhost.
de uma olhada nos videos , essas aulas estao em video no meu canal do youtube 
https://youtube.com/playlist?list=PLr9-FeATlrPLsx5904LWpNml0a4aSSA5h

**Comment by igorkeven** [comment]
não , não precisa, uso o servidor local da máquina, o localhost.
tenho um vídeo criando esse e outras formas de login no meu canal no youtube.
https://www.youtube.com/@igorkeven
